engineSearch/Shakespeare/urls.py
from django.urls import path

from . import views

app_name = 'Shakespeare'
urlpatterns = [
    # ex: /searchShakespeare/
    path('', views.index, name='index'),
    # ex: /searchShakespeare/5/
    path('<int:pk>/content/', views.detail, name='detail'),
    # ex: /searchShakespeare/result/
    path('results/', views.results, name='results'),
]

engineSearch/searchText/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('searchShakespeare/', include('Shakespeare.urls')),
]

engineSearch/Shakespeare/models.py
import datetime

from django.db import models
from django.utils import timezone


class Category(models.Model):
    category_name = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.category_name

    # def was_published_recently(self):
    #     now = timezone.now()
    #     return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Work(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    work_name = models.CharField(max_length=200)
    work_fname = models.CharField(max_length=50, default="") # django provide FileField, FilePathField, TextField # ref: https://docs.djangoproject.com/en/4.0/ref/models/fields/
    # votes = models.IntegerField(default=0)

    def __str__(self):
        return self.work_name

engineSearch/Shakespeare/views.py
import csv, os

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.template import loader

from .models import Work, Category

import logging
logger = logging.getLogger("mylogger")


def index(request):
    categories = Category.objects.all()
    context = {  # target of template
        'category_list': categories,
    }
    return render(request, 'Shakespeare/index.html', context)


def detail(request, pk):
    work = Work.objects.get(pk=pk)
    path = os.path.join('./Shakespeare/.data', work.work_fname)
    with open(path, 'r') as f:
        lines = f.readlines()
    context = {
        'content': "".join(lines)
    }
    return render(request, 'Shakespeare/detail.html', context)


def results(request):
    term_by_document = {}
    with open("./Shakespeare/.data/term_by_document.csv", 'r') as f:
        rows = csv.DictReader(f)
        for row in rows:
            term_by_document.setdefault(row['term'], []).append(row['document'])

    def operation(set1, set2, op):
        if op == 'OR':
            return set1 | set2
        return set1 & set2  # case: operation == 'AND'

    def query(operations):
        operations = operations.lower().split()
        stack = []
        for ch in operations:
            if ch == ')':
                ch = stack.pop()
                if isinstance(ch, str):
                    ch = set("".join(term_by_document.get(ch, set())).split(','))
                operator = stack.pop()
                if operator != '(': # either '(' or a operator (AND, OR)
                    set2 = stack.pop()
                    if isinstance(set2, str):
                        set2 = set("".join(term_by_document.get(set2, set())).split(','))
                    stack.pop()  # '('
                    ch = operation(ch, set2, operator.upper())
            stack.append(ch)
        return list(stack[0]) or -1  # -1 if not found
    documents = query(request.POST['keywords'])
    works = Work.objects.filter(work_fname__in=documents)
    context = {
        'work_list': works,
    }
    return render(request, 'Shakespeare/results.html', context) if works else HttpResponse("No result")

engineSearch/Shakespeare/templates/Shakespeare/detail.html
<pre>{{ content }}</pre>

engineSearch/Shakespeare/templates/Shakespeare/index.html
<html>
<head></head>
<body>
<form  style="text-align: center; " action="{% url 'Shakespeare:results' %}" method="post">
{% csrf_token %}
    <legend><h1>Search Shakespeare</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <input type="text" name="keywords" size="30"> <input type="submit" value="Search">
</form>
</body>
</html>


<!--To make the tutorial shorter, all template examples use incomplete HTML.
In your own projects you should use complete HTML documents.-->

engineSearch/Shakespeare/templates/Shakespeare/results.html
<h1>Result</h1>

<ul>
{% for work in work_list %}
    <li>
    <a href="{% url 'Shakespeare:detail' work.id %}">{{ work.work_name }} -- {{ work.category }}</a>
    </li>
{% endfor %}
</ul>


<!--
{% if category_list %}
    <ul>
    {% for category in category_list %}
        <li><a href="{% url 'Shakespeare:detail' %}">{{ category.category_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No categories :/</p>
{% endif %}
-->